name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install
        working-directory: ./voice-shooter
      - name: npm run build
        run: npm run build
        working-directory: ./voice-shooter
      - name: npm run lint
        run: npm run lint
        working-directory: ./voice-shooter