name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install
        working-directory: ./textalive-sample
      - name: npm run lint
        run: npm run lint
        working-directory: ./textalive-sample